### ISSUE TITLE
Add batch id generation

### ISSUE THREAD

**Issue by antongolub** [qiwi/flp-njs#9]
https://github.com/qiwi/flp-njs/blob/566c15bd991d90cadc64a1d36af4ace762dfea86/src/main/njs/formatters.js#L61

**Comment by oljekechoro** [comment]
What do you think about using `crypto.createHash` with `r.requestText`?

**Comment by antongolub** [comment]
Messages may not be unique. We need some kind of random for ids.
```js
(Math.random()).toString(36).slice(2)
```
